### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Razican** [SUPERAndroidAnalyzer/super#60]
This issue tracks the documentation of different modules in SUPER. Each module has its own issue:
- [x] [`main.rs` (#54)](https://github.com/SUPERAndroidAnalyzer/super/issues/54)
- [x] [`lib.rs` (#147)](https://github.com/SUPERAndroidAnalyzer/super/issues/147)
- [ ] `cli.rs`
- [ ] [`config.rs` (#55)](https://github.com/SUPERAndroidAnalyzer/super/issues/55)
- [ ] `criticality.rs`
- [x] [`decompilation.rs` (#56)](https://github.com/SUPERAndroidAnalyzer/super/issues/56)
- [ ] `error.rs`
- [ ] [`utils.rs` (#57)](https://github.com/SUPERAndroidAnalyzer/super/issues/57)
- [ ] `results` module:
  - [ ] [`results/mod.rs` (#58)](https://github.com/SUPERAndroidAnalyzer/super/issues/58)
  - [ ] [`results/utils.rs` (#59)](https://github.com/SUPERAndroidAnalyzer/super/issues/59)
  - [ ] `handlebars_helpers.rs`
  - [ ] `sdk_numbers.rs`
  - [ ] `report` submodule:
    - [ ] `report/mod.rs`
    - [ ] `report/handlebars.rs`
    - [ ] `report/json.rs`
- [ ] `static_analysis` module:
  - [x] [`static_analysis/mod.rs` (#61)](https://github.com/SUPERAndroidAnalyzer/super/issues/61)
  - [ ] [`static_analysis/certificate.rs` (#62)](https://github.com/SUPERAndroidAnalyzer/super/issues/62)
  - [ ] [`static_analysis/code.rs` (#64)](https://github.com/SUPERAndroidAnalyzer/super/issues/64)
  - [ ] [`static_analysis/manifest.rs` (#65)](https://github.com/SUPERAndroidAnalyzer/super/issues/65)
